# Default values for common-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: avivacr13.azurecr.io/docker/rabbit-flask-rerun
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.0.1"

imagePullSecrets: []
nameOverride: "rabbit-trigger-flask"
fullnameOverride: "rabbit-trigger-flask"

commonEnv:
  - name: StorageConnectionString
    value: "DefaultEndpointsProtocol=https;AccountName=avivblob;AccountKey=BZcRSYm5HUiXgLz3aWCEygw6ECy8RHKBAzlpJmUkYBtiUpdaxixRGz2D/t+ExznpeHKYuFnKTL7H+AStJzIo5A==;EndpointSuffix=core.windows.net"
  - name: Container
    value: "datatest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: rabbit-trigger-flask
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
